### ISSUE TITLE
 Signal-Desktop never leaves the "loading" screen with the 3 animated dots when running on fully updated Fedora 34

### ISSUE THREAD

**Issue by maitra** [luminoso/fedora-copr-signal-desktop#10]
Hi,

Not sure what to report but I am having the problem since last evening (27 August).  I get the following when I run on the commandline.

```
{"level":30,"time":"2021-08-28T13:31:58.903Z","pid":477961,"hostname":"hiidden","msg":"System tray service: showing the window from the context menu"}
{"level":30,"time":"2021-08-28T13:31:58.912Z","pid":477961,"hostname":"hidden","msg":"System tray service: rendering the tray"}
{"level":30,"time":"2021-08-28T13:31:59.422Z","pid":477961,"hostname":"hidden","msg":"Updating BrowserWindow config: {\"maximized\":false,\"autoHideMenuBar\":false,\"fullscreen\":false,\"width\":2506,\"height\":1419,\"x\":54,\"y\":18}"}
{"level":30,"time":"2021-08-28T13:31:59.423Z","pid":477961,"hostname":"hidden","msg":"config/set: Saving ephemeral config to disk"}

```

Have not had this problem before. Signal on the phone connects and works as usual.

**Comment by tardfree** [comment]
I have the same problem, with package signal-desktop-5.15.0-1.fc34.x86_64 so I tried to roll back to the previous version.
I see that 5.15 is no longer in the repo, as I rolled back only to discover the repository now has up to signal-desktop-5.14.0-1.fc34.x86_64

Unfortunately for me, the db schema update for 5.15 has occurred, so 5.14 will not load now either without deleting all data.

**Comment by maitra** [comment]
> I have the same problem, with package signal-desktop-5.15.0-1.fc34.x86_64 so I tried to roll back to the previous version.
> I see that 5.15 is no longer in the repo, as I rolled back only to discover the repository now has up to signal-desktop-5.14.0-1.fc34.x86_64
> 
> Unfortunately for me, the db schema update for 5.15 has occurred, so 5.14 will not load now either without deleting all data.

Same here, I just deleted the data and moved on. I wonder why the db schema needed to be deleted in the first place.

**Comment by luminoso** [comment]
let's track this one on issue #9
