### ISSUE TITLE
signal-desktop is now behind (5.29.1 upstream, 5.28.0 here) and no longer allowed to connect by signal

### ISSUE THREAD

**Issue by maitra** [luminoso/fedora-copr-signal-desktop#14]
signal-desktop on copr needs an update to the latest version.

**Comment by RES-1** [comment]
The same here.

![Bildschirmkopie](https://user-images.githubusercontent.com/4004046/151128580-6f52712f-43d7-4e74-8cad-d4ab4088595a.png)

**Comment by MichaelBitard** [comment]
This failed on opensuse only, if you use fedora, you can download the rpm from here https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/build/3227656/ and install it

**Comment by MichaelBitard** [comment]
I have the 5.29.0 from the rpm and I still have this message though

**Comment by RES-1** [comment]
> I have the 5.29.0 from the rpm and I still have this message though

The same here.

Apparently "5.29.1" must be used.

**Comment by kwizart** [comment]
I've made a quick update based on Guilherme package.
https://dl.kwizart.net/signal-desktop-5.29.1-1.fc35.x86_64.rpm

Here is the source package with few updated changes...
https://dl.kwizart.net/signal-desktop-5.29.1-1.fc35.src.rpm

**Comment by luminoso** [comment]
You are right. Don't know why but I didn't notice this update.
Pushed 5.29.1.

**Comment by RES-1** [comment]
> You are right. Don't know why but I didn't notice this update. Pushed 5.29.1.

Strange. When I install "https://dl.kwizart.net/signal-desktop-5.29.1-1.fc35.x86_64.rpm" it works. When I install the latest version via "Copr", it also says the version is out of date, even though it's also the "5.29.1" version.

**Comment by luminoso** [comment]
What distribution are you using?

**Comment by RES-1** [comment]
> What distribution are you using?

"Fedora release 35 (Thirty Five)"

**Comment by pkotvan** [comment]
> > You are right. Don't know why but I didn't notice this update. Pushed 5.29.1.
> 
> Strange. When I install "https://dl.kwizart.net/signal-desktop-5.29.1-1.fc35.x86_64.rpm" it works. When I install the latest version via "Copr", it also says the version is out of date, even though it's also the "5.29.1" version.

I have the same experience, using Fedora 35, updated to signal-desktop-5.29.1-1.fc35.x86_64 from the copr repository and I still get the _out of date_ message.

**Comment by kwizart** [comment]
Maybe one needs to verify that the previous process is fully killed ?
ps -ef |grep signal-desktop ?
killall signal-desktop

Then relaunch.

**Comment by MichaelBitard** [comment]
even relaunched, after reboot and such, still nothing

**Comment by RES-1** [comment]
> Maybe one needs to verify that the previous process is fully killed ? ps -ef |grep signal-desktop ? killall signal-desktop

It's not because of that. The new version is actually active.

![Bildschirmkopie](https://user-images.githubusercontent.com/4004046/151150269-a8319475-03ba-405f-9aa8-5a9dcfc002a4.png)

**Comment by luminoso** [comment]
Ok it looks like it is related to Copr and fedora rpm macros. 
Upstream discussion [here](https://bugzilla.redhat.com/show_bug.cgi?id=1793722)

Pushed Copr update for 5.29.1-2 that should fix the issuse.

Update via: `sudo dnf --refresh upgrade signal-desktop`

**Comment by RES-1** [comment]
> Pushed Copr update for 5.29.1-2 that should fix the issuse.

It works now. Many Thanks.
