### ISSUE TITLE
Remove GConf dependency

### ISSUE THREAD

**Issue by aklapper** [luminoso/fedora-copr-signal-desktop#15]
Following https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/ , after `sudo dnf copr enable luminoso/Signal-Desktop` and `sudo dnf install signal-desktop`, dnf wants to install `GConf2` which is an ancient unmaintained GNOME backend. https://github.com/signalapp/Signal-Desktop/issues/2344 implies that this should not be needed.

**Comment by luminoso** [comment]
Thank you for the heads up! Will do a rebuild without it and ping here once done

**Comment by luminoso** [comment]
Bump. Removed GConf dependency.

Update via: `sudo dnf --refresh upgrade signal-desktop`

**Comment by aklapper** [comment]
Confirming for `5.29.1-3.fc35`, thanks a lot for the quick fix!

**Comment by aklapper** [comment]
(I'm also still a bit surprised to see packages like `libappindicator-gtk3`, `libdbusmenu`, `libdbusmenu-gtk3`, `libindicator-gtk3` listed as dependencies to be installed. Are you sure those are really required?)

**Comment by luminoso** [comment]
I just mimic the debian dependencies to Fedora when back then I created the package.
And you're right. I never made a review if they're still up to date.

What is listed as dependency is: `libnotify, libappindicator-gtk3, libXtst, nss, libXScrnSaver` 

and their upstream requirements list is: https://github.com/signalapp/Signal-Desktop/blob/ec04e520ecfdae7360dfb36faafa2c01878a9cc2/package.json#L386

maybe `libXScrnSaver` and `libappindicator-gtk3` are already deprecated too. I'll experiment removing them on the next build

**Comment by luminoso** [comment]
Done. Pushed `5.30.0-1` where `libXScrnSaver` and `libappindicator-gtk3` are removed. please report any issues
