### ISSUE TITLE
signal-desktop is now behind (5.35.0 upstream, 5.34.0 here) 

### ISSUE THREAD

**Issue by maitra** [luminoso/fedora-copr-signal-desktop#17]
I don't know if this is related, but I have some issues with running it in the background on my desktop. Get an exception error: quit/copy error and quit repeatedly. In the past, updates have often addressed this problem for me. Right now, I am running it in the foreground.

Thank you very much for your work in making fedora builds and in maintaining this repo.

**Comment by luminoso** [comment]
I'm sorry, for some reason I totally missed this issue.

Which I assume is no longer an issue. Closing
