### ISSUE TITLE
Weird issue with Signal crashing

### ISSUE THREAD

**Issue by Rudd-O** [luminoso/fedora-copr-signal-desktop#18]
Hi!  How do I send a coredump safely for analysis?  Thanks.

**Comment by luminoso** [comment]
Hum.. not sure if you can. What issue are you having?

**Comment by Rudd-O** [comment]
Signal from COPR sometimes just... crashes, no explanation as to why.  I have a coredump available to send, but I am concerned about posting such a coredump on a public bug tracker.

**Comment by luminoso** [comment]
My advise if for you to test any of the Signal packaging alternatives:

- [Flatpak release](https://flathub.org/apps/details/org.signal.Signal)
- [OpenSuse BuildSystem Signal Community project](https://software.opensuse.org/package/signal-desktop)

**Comment by Rudd-O** [comment]
Uh I don't want to install a Flatpak.  Let me close this.
