### ISSUE TITLE
Tray icon stopped working on Fedora after signal-desktop-1.31.0-5

### ISSUE THREAD

**Issue by ykne** [luminoso/fedora-copr-signal-desktop#2]
Has signal-desktop changed tray icon code?
However original signal-desktop from on Ubuntu has no problems displaying tray icon.
Other desktop applications like Xpad continue showing its icons as usual.

**Comment by luminoso** [comment]
I did indeed made changes in the code, but nothing related to the tray icon.

- Which display manager are you using?
- Fedora version? Is it fully updated?
- Can you please show me `/usr/share/applications/signal-desktop.desktop` file contents?
- Can you please try launching signal via terminal like this: `signal-desktop --use-tray-icon` and see if that works?

**Comment by ykne** [comment]
I am using GNOME, fresh clean Fedora 31 and 32 default setup in pristine test environment, gnome-shell-extension-topicons-plus package installed for icons to work. `signal-desktop.desktop` are correct, application behaviour after launch from menu and command line is identical.
If `signal-desktop-1.31.0-5.fc31.x86_64.rpm` is installed in Fedora 32 then tray icon appears.
I did not see any tray icon related changes in spec file as well so it must be in signal-desktop code itself between included in 1.31.0-5 and next version rpm package.

**Comment by luminoso** [comment]
I've tested and I can replicate the issue.

It looks like being tracked by Signal-Desktop team: https://github.com/signalapp/Signal-Desktop/issues/4132 

Maybe Signal's [change from electron 6.x to 8.x between signal release 1.31.x and 1.33.x](https://github.com/signalapp/Signal-Desktop/compare/v1.31.0...v1.33.4) may have triggered an electron issue: https://github.com/electron/electron/issues/21445

I don't see anything that I can do in the build process to mitigate the issue

**Comment by ykne** [comment]
Thank you for providing references. However I am puzzled why tray icon issue is not reproducible in GNOME Ubuntu 18.04 LTS. Signal-desktop is installed according to official instructions.
What is present in Ubuntu GNOME which missing in other distributions?

**Comment by luminoso** [comment]
From what I saw maybe it is `libdbusmenu-gtk4`. On Fedora the maximum gtk version that i see for libdbusmenu is gtk3

**Comment by ykne** [comment]
Do you know how to find exact set of changes in signal-desktop code between 1.31.0-5 and next rpm? Only new electron or other code changes?

**Comment by luminoso** [comment]
A lot of other changes also. [Here](https://github.com/signalapp/Signal-Desktop/compare/v1.31.0...v1.33.4) you can see the changelist and also the code that changed between 1.31.0 and 1.33.4

**Comment by ykne** [comment]
I wonder if reverting a switch to electron 8 in [package.json](https://github.com/signalapp/Signal-Desktop/commit/2f9bebe5676845949a3e3beb9655dfd1bc018b80#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) restores tray icon and does not cause negative effects.

**Comment by luminoso** [comment]
I patched package.json and did a build with electron 6.1.11

You can download the result here: [signal-desktop-1.33.4-1.fc32.x86_64.rpm
](https://drive.google.com/open?id=1LaZpeGassXNT4XlLqDghfF3TWOYfubqy)
I didn't test it. If you want to give it a try please report if it works.

**Comment by ykne** [comment]
Surprisingly, did not help. Apparently the problem is someplace else.

**Comment by luminoso** [comment]
Hum.. I don't have any more ideas how to solve this in the build-layer.
I think for now the best is to wait for the upstream fix, unless you have any other recommendation

**Comment by luminoso** [comment]
Sorry, I double checked and I didn't correctly patched the spec file to build with electron 6.
That last rpm was still built against electron 8.x

Can you please re-test with this one?

[signal-desktop-eletron6-1.33.4-1.fc32.x86_64.rpm
](https://drive.google.com/open?id=10ewWmZAS2c69u5NRIRehzEIKhzPuok0h)

**Comment by ykne** [comment]
Unhandled Promise Rejection: TypeError: Cannot read property 'includes' of undefined
    at /usr/lib64/signal-desktop/resources/app.asar/app/spell_check.js:12:22
    at Array.filter (<anonymous>)
    at getLanguages (/usr/lib64/signal-desktop/resources/app.asar/app/spell_check.js:11:59)
    at exports.setup (/usr/lib64/signal-desktop/resources/app.asar/app/spell_check.js:28:21)
    at createWindow (/usr/lib64/signal-desktop/resources/app.asar/main.js:329:3)
    at async App.<anonymous> (/usr/lib64/signal-desktop/resources/app.asar/main.js:930:3)

**Comment by luminoso** [comment]
Humm ok. Let's see how upstream progresses then

**Comment by ykne** [comment]
Tray icon appears to work in recent builds.

**Comment by luminoso** [comment]
Awesome. So it was indeed an upstream issue. Thank you for letting me know. Closing
