### ISSUE TITLE
Packages conflict in /usr/lib/.build-id/

### ISSUE THREAD

**Issue by sebastianelsner** [luminoso/fedora-copr-signal-desktop#6]
I have Signal (from this copr), VSCodium and VSCode installed and I am seeing this issue:

https://www.mail-archive.com/devel@lists.fedoraproject.org/msg163999.html

It has been solved like this for VSCode:

https://github.com/microsoft/vscode/pull/116105#issue-569471380

**Comment by luminoso** [comment]
Just released 1.40.1. Can you check if the trick solves the issue?

**Comment by sebastianelsner** [comment]
Thank you for checking. I am still on fc32. Will try to update and let you know.

**Comment by colorizer** [comment]
Yes, 1.40.1 installed without issues in fedora 33.

**Comment by sebastianelsner** [comment]
Works for me as well. Thank you very much!
