### ISSUE TITLE
Difference between build script in OBS

### ISSUE THREAD

**Issue by jacksongoode** [luminoso/fedora-copr-signal-desktop#8]
Just wondering the difference? It seems I can't install from the OBS anyway because of missing `libopenssl`.

**Comment by luminoso** [comment]
What does OBS stand for?

**Comment by jacksongoode** [comment]
Sorry, OpenSuse's open build service.

**Comment by luminoso** [comment]
To my understanding (and I guess this is related to https://github.com/signalapp/Signal-Desktop/issues/1630), the [Signal build on OBS ](https://build.opensuse.org/project/show/network:im:signal) is trying to accomplish different things:

- Reproducible builds
- Drop the usage of Signal's self built in binaries (e.g. [zkgroup](https://github.com/signalapp/zkgroup)) with ones build-from-source by their own

To do so they have to pull and build everything that supports the final signal-desktop compilation. So it is a whole new level of effort that I didn't try to solve.

In contrast, this copr package builds https://github.com/signalapp/Signal-Desktop from source as is. An approach identical to Archlinux [is doing](https://github.com/archlinux/svntogit-community/blob/packages/signal-desktop/trunk/PKGBUILD).

The only patches that you see in the rpm spec file is to strip the building the .deb package and to avoid to pull packages related to OSX.

Other than that the signal-desktop repo is cloned, built and packaged, including the binary blobs that Signal team provides (and uses?) in their own sources and repository.

Does this answer your question?

**Comment by jacksongoode** [comment]
Great explanation! Thanks a lot!
